// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Gm5g-QDqi52JynnAucBh-dRtNhMzXIY',
    appId: '1:701262945529:web:914f47a2954a77e88c9628',
    messagingSenderId: '701262945529',
    projectId: 'fairwayfinder-87d30',
    authDomain: 'fairwayfinder-87d30.firebaseapp.com',
    storageBucket: 'fairwayfinder-87d30.appspot.com',
    measurementId: 'G-9E191HBXES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDofPdAYf1Xh9mYy7qndLvOIk7gsPYMhKk',
    appId: '1:701262945529:android:f6cd471759d24d178c9628',
    messagingSenderId: '701262945529',
    projectId: 'fairwayfinder-87d30',
    storageBucket: 'fairwayfinder-87d30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA91rDXqEMgL5u3YUnyLWjT6xXkiYDwvZM',
    appId: '1:701262945529:ios:c6161bb08ae0bd538c9628',
    messagingSenderId: '701262945529',
    projectId: 'fairwayfinder-87d30',
    storageBucket: 'fairwayfinder-87d30.appspot.com',
    iosBundleId: 'com.example.fairwayfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA91rDXqEMgL5u3YUnyLWjT6xXkiYDwvZM',
    appId: '1:701262945529:ios:c6161bb08ae0bd538c9628',
    messagingSenderId: '701262945529',
    projectId: 'fairwayfinder-87d30',
    storageBucket: 'fairwayfinder-87d30.appspot.com',
    iosBundleId: 'com.example.fairwayfinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Gm5g-QDqi52JynnAucBh-dRtNhMzXIY',
    appId: '1:701262945529:web:97fb0ba956c7b5838c9628',
    messagingSenderId: '701262945529',
    projectId: 'fairwayfinder-87d30',
    authDomain: 'fairwayfinder-87d30.firebaseapp.com',
    storageBucket: 'fairwayfinder-87d30.appspot.com',
    measurementId: 'G-4V0BSBDF2N',
  );
}
